# Generated by Django 2.0.3 on 2019-07-09 14:51

from django.db import migrations, models
import django_redshift_backend.distkey


class Migration(migrations.Migration):

    dependencies = [
        ('lg_pricing', '0002_auto_20190705_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='LgRsEntityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_history_id', models.IntegerField()),
                ('entity_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('picture_count', models.IntegerField(blank=True, null=True)),
                ('video_count', models.IntegerField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('review_avg_score', models.FloatField(blank=True, null=True)),
                ('store_id', models.IntegerField()),
                ('store_name', models.CharField(max_length=256)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=256)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=256)),
                ('brand_id', models.IntegerField()),
                ('brand_name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField()),
                ('sku', models.CharField(blank=True, max_length=256, null=True)),
                ('sku_url', models.URLField(max_length=512)),
                ('sku_name', models.CharField(blank=True, max_length=256, null=True)),
                ('cell_plan_id', models.IntegerField(blank=True, null=True)),
                ('cell_plan_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [django_redshift_backend.distkey.DistKey(fields=['product_id'], name='lg_pricing__product_1d2783_idx')]
            },
        )
    ]
