# Generated by Django 5.0 on 2024-03-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg_pricing', '0003_auto_20190709_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='LgRsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=255)),
                ('brand_id', models.IntegerField()),
                ('brand_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('spec_num_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spec_num_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spec_num_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spec_num_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spec_num_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spec_txt_1', models.CharField(blank=True, max_length=256, null=True)),
                ('spec_txt_2', models.CharField(blank=True, max_length=256, null=True)),
                ('spec_txt_3', models.CharField(blank=True, max_length=256, null=True)),
                ('spec_txt_4', models.CharField(blank=True, max_length=256, null=True)),
                ('spec_txt_5', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
