# Generated by Django 2.0.3 on 2019-02-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0033_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ('update', 'asset'),
            },
        ),
        migrations.CreateModel(
            name='BannerAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.URLField()),
            ],
            options={
                'ordering': ('picture_url',),
            },
        ),
        migrations.CreateModel(
            name='BannerAssetContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.BannerAsset')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
            ],
            options={
                'ordering': ('asset', 'brand', 'category'),
            },
        ),
        migrations.CreateModel(
            name='BannerUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Store')),
            ],
            options={
                'ordering': ('store', 'timestamp'),
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.BannerAsset'),
        ),
        migrations.AddField(
            model_name='banner',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.BannerUpdate'),
        ),
    ]
