# Generated by Django 2.0.3 on 2019-02-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0033_brand'),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('update', 'asset', 'category')},
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category'),
        ),
        migrations.AddField(
            model_name='bannerasset',
            name='key',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
