# Generated by Django 2.0.3 on 2019-02-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20190214_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerasset',
            name='key',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
