# Generated by Django 2.0.3 on 2019-02-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20190214_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('update', 'asset', 'category'), 'permissions': (['backend_list_banners', 'Can see banner list in the backend'],)},
        ),
    ]
