# Generated by Django 2.0.3 on 2019-02-14 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20190214_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerasset',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
