# Generated by Django 2.0.3 on 2019-02-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_bannerasset_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('update', 'asset', 'category', 'position'), 'permissions': (['backend_list_banners', 'Can see banner list in the backend'],)},
        ),
        migrations.AlterModelOptions(
            name='bannerasset',
            options={'ordering': ('picture_url',), 'permissions': (['is_staff_of_banner_assets', 'Is staff of all banner assets'],)},
        ),
        migrations.AlterField(
            model_name='bannerassetcontent',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='banners.BannerAsset'),
        ),
    ]
