# Generated by Django 2.0.3 on 2019-02-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0036_auto_20190220_1306'),
        ('banners', '0006_auto_20190220_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bannerasset',
            options={'ordering': ('picture_url', 'id'), 'permissions': (['is_staff_of_banner_assets', 'Is staff of all banner assets'],)},
        ),
    ]
