# Generated by Django 2.0.3 on 2019-02-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_auto_20190225_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('update', 'asset', 'section', 'position'), 'permissions': (['backend_list_banners', 'Can see banner list in the backend'],)},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='category',
        ),
        migrations.AddField(
            model_name='banner',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banners.BannerSection'),
            preserve_default=False,
        ),
    ]
