# Generated by Django 2.0.3 on 2019-02-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_auto_20190225_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannersection',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category'),
        ),
    ]
