# Generated by Django 2.0.3 on 2019-02-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0009_auto_20190225_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BannerSubsectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('storescraper_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('update', 'asset', 'position'), 'permissions': (['backend_list_banners', 'Can see banner list in the backend'],)},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='section',
        ),
        migrations.RemoveField(
            model_name='bannersection',
            name='category',
        ),
        migrations.AddField(
            model_name='bannersection',
            name='name',
            field=models.CharField(default='old', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannersubsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.BannerSection'),
        ),
        migrations.AddField(
            model_name='bannersubsection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.BannerSubsectionType'),
        ),
    ]
