# Generated by Django 2.0.3 on 2019-02-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0010_auto_20190226_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subsection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banners.BannerSubsection'),
            preserve_default=False,
        ),
    ]
