# Generated by Django 2.0.3 on 2019-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0011_banner_subsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannersection',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='bannersubsection',
            options={'ordering': ('section', 'name')},
        ),
        migrations.AlterModelOptions(
            name='bannersubsectiontype',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(default='https://www.example.com'),
            preserve_default=False,
        ),
    ]
