# Generated by Django 2.0.3 on 2019-02-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0012_auto_20190226_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('update', 'position', 'asset'), 'permissions': (['backend_list_banners', 'Can see banner list in the backend'],)},
        ),
    ]
