# Generated by Django 2.0.3 on 2019-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0013_auto_20190226_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='destination_urls',
            field=models.CharField(default='https://www.example.com', max_length=255),
            preserve_default=False,
        ),
    ]
