# Generated by Django 2.0.3 on 2019-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0015_auto_20190304_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerupdate',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
