# Generated by Django 2.0.3 on 2019-03-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0016_auto_20190304_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerupdate',
            old_name='message',
            new_name='status_message',
        ),
    ]
