# Generated by Django 2.0.3 on 2019-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0017_auto_20190304_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='destination_urls',
            field=models.CharField(max_length=512),
        ),
    ]
