# Generated by Django 2.0.3 on 2019-04-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0018_auto_20190313_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerupdate',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
