# Generated by Django 4.2.3 on 2023-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0019_auto_20190409_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerasset',
            name='picture_url',
            field=models.URLField(max_length=255),
        ),
    ]
