# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0102_categoryspecsorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecsFormFieldset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ordering', models.IntegerField()),
            ],
            options={
                'ordering': ('layout', 'ordering'),
            },
        ),
        migrations.CreateModel(
            name='CategorySpecsFormFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ordering', models.IntegerField()),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_specs_forms.CategorySpecsFormFieldset')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.CategorySpecsFilter')),
            ],
            options={
                'ordering': ('fieldset', 'ordering'),
            },
        ),
        migrations.CreateModel(
            name='CategorySpecsFormLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.ApiClient')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
            ],
            options={
                'ordering': ('category', 'api_client', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CategorySpecsFormOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ordering', models.IntegerField()),
                ('suggested_use', models.CharField(choices=[('gte', 'High to low'), ('lte', 'Low to high'), ('both', 'Both')], max_length=20)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_specs_forms.CategorySpecsFormLayout')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.CategorySpecsOrder')),
            ],
            options={
                'ordering': ('layout', 'ordering'),
            },
        ),
        migrations.AddField(
            model_name='categoryspecsformfieldset',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_specs_forms.CategorySpecsFormLayout'),
        ),
    ]
