# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0009_auto_20171114_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecsFormColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('ordering', models.IntegerField()),
            ],
            options={
                'ordering': ('layout', 'ordering'),
            },
        ),
        migrations.CreateModel(
            name='CategorySpecsFormFieldset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ordering', models.IntegerField()),
            ],
            options={
                'ordering': ('layout', 'ordering'),
            },
        ),
        migrations.CreateModel(
            name='CategorySpecsFormFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ordering', models.IntegerField()),
                ('continuous_range_step', models.IntegerField(blank=True, null=True)),
                ('continuous_range_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='category_specs_forms.CategorySpecsFormFieldset')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.CategorySpecsFilter')),
            ],
            options={
                'ordering': ('fieldset', 'ordering'),
            },
        ),
        migrations.CreateModel(
            name='CategorySpecsFormLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Country')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Website')),
            ],
            options={
                'ordering': ('category', 'website', 'country', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CategorySpecsFormOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ordering', models.IntegerField()),
                ('suggested_use', models.CharField(choices=[('ascending', 'Ascending'), ('descending', 'Descending'), ('both', 'Both')], max_length=20)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='category_specs_forms.CategorySpecsFormLayout')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.CategorySpecsOrder')),
            ],
            options={
                'ordering': ('layout', 'ordering'),
            },
        ),
        migrations.AddField(
            model_name='categoryspecsformfieldset',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='category_specs_forms.CategorySpecsFormLayout'),
        ),
        migrations.AddField(
            model_name='categoryspecsformcolumn',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='category_specs_forms.CategorySpecsFormLayout'),
        ),
    ]
