# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0001_initial'),
        ('category_specs_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryspecsformorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.CategorySpecsOrder'),
        ),
        migrations.AddField(
            model_name='categoryspecsformlayout',
            name='api_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.ApiClient'),
        ),
        migrations.AddField(
            model_name='categoryspecsformlayout',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category'),
        ),
        migrations.AddField(
            model_name='categoryspecsformlayout',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Country'),
        ),
        migrations.AddField(
            model_name='categoryspecsformfilter',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='category_specs_forms.CategorySpecsFormFieldset'),
        ),
        migrations.AddField(
            model_name='categoryspecsformfilter',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.CategorySpecsFilter'),
        ),
        migrations.AddField(
            model_name='categoryspecsformfieldset',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='category_specs_forms.CategorySpecsFormLayout'),
        ),
    ]
