# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0009_auto_20171114_2039'),
        ('category_specs_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryspecsformlayout',
            options={'ordering': ('category', 'website', 'name')},
        ),
        migrations.RemoveField(
            model_name='categoryspecsformlayout',
            name='country',
        ),
        migrations.AddField(
            model_name='categoryspecsformfilter',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Country'),
        ),
        migrations.AddField(
            model_name='categoryspecsformorder',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Country'),
        ),
    ]
