# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_specs_forms', '0002_auto_20171017_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryspecsformorder',
            name='suggested_use',
            field=models.CharField(choices=[('ascending', 'Ascending'), ('descending', 'Descending'), ('both', 'Both')], max_length=20),
        ),
    ]
