# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_specs_forms', '0002_auto_20171123_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryspecsformcolumn',
            name='layout',
        ),
        migrations.DeleteModel(
            name='CategorySpecsFormColumn',
        ),
    ]
