# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_specs_forms', '0002_auto_20171010_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryspecsformlayout',
            options={'ordering': ('category', 'api_client', 'country', 'name')},
        ),
    ]
