# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_specs_forms', '0003_auto_20171031_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecsFormColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('ordering', models.IntegerField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='category_specs_forms.CategorySpecsFormLayout')),
            ],
            options={
                'ordering': ('layout', 'ordering'),
            },
        ),
    ]
