# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_specs_forms', '0003_auto_20171011_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryspecsformfilter',
            name='continuous_range_step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
