# Generated by Django 2.0.3 on 2019-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_specs_forms', '0003_auto_20171124_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryspecsformfilter',
            name='continuous_range_step',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
