# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_specs_forms', '0004_categoryspecsformfilter_continuous_range_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryspecsformfilter',
            name='continuous_range_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
