# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_specs_forms', '0004_categoryspecsformcolumn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryspecsformlayout',
            options={'ordering': ('category', 'website', 'country', 'name')},
        ),
        migrations.RenameField(
            model_name='categoryspecsformlayout',
            old_name='api_client',
            new_name='website',
        ),
    ]
