# Generated by Django 2.0.3 on 2020-05-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0063_entity_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrositeBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('fields', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='MicrositeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=1)),
                ('home_ordering', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(max_length=256)),
                ('brand_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_attr_1_str', models.CharField(blank=True, max_length=256, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='microsite.MicrositeBrand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='micrositeentry',
            unique_together={('brand', 'product')},
        ),
    ]
