# Generated by Django 2.0.3 on 2020-06-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='micrositebrand',
            options={'permissions': (['view_microsite_brand', 'Can see the brand'], ['change_microsite_brand', 'Can edit brand entries'], ['pricing_view_microsite', 'Can see microsite view on pricing'])},
        ),
    ]
