# Generated by Django 2.0.3 on 2020-06-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0064_product_part_number'),
        ('microsite', '0002_auto_20200602_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='micrositeentry',
            options={'ordering': ('product__instance_model__model__category', 'ordering')},
        ),
        migrations.AddField(
            model_name='micrositebrand',
            name='brand',
            field=models.ForeignKey(default=848, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='micrositeentry',
            name='sku',
            field=models.CharField(default='', max_length=256),
        ),
    ]
