# Generated by Django 2.0.3 on 2020-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsite', '0003_auto_20200605_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositeentry',
            name='ordering',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
