# Generated by Django 2.0.3 on 2020-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsite', '0004_auto_20200608_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositeentry',
            name='sku',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
