# Generated by Django 2.0.3 on 2020-06-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsite', '0006_auto_20200609_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositeentry',
            name='custom_attr_2_str',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='micrositeentry',
            name='custom_attr_3_str',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='micrositeentry',
            name='custom_attr_4_str',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='micrositeentry',
            name='custom_attr_5_str',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
