# Generated by Django 2.0.3 on 2018-06-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='RSCountry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='RSCurrency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('iso_code', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exchange_rate_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='RSEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=50, null=True)),
                ('sku', models.CharField(max_length=50, null=True)),
                ('ean', models.CharField(max_length=15, null=True)),
                ('key', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=512)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='RSEntityHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('stock', models.IntegerField()),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cell_monthly_payment', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.RSEntity')),
            ],
            options={
                'db_table': 'entity_history',
            },
        ),
        migrations.CreateModel(
            name='RSProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.RSCategory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='RSStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.RSCountry')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='RSStoreType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'store_type',
            },
        ),
        migrations.AddField(
            model_name='rsstore',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.RSStoreType'),
        ),
        migrations.AddField(
            model_name='rsentity',
            name='active_registry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analytics.RSEntityHistory'),
        ),
        migrations.AddField(
            model_name='rsentity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.RSCategory'),
        ),
        migrations.AddField(
            model_name='rsentity',
            name='cell_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analytics.RSProduct'),
        ),
        migrations.AddField(
            model_name='rsentity',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.RSCurrency'),
        ),
        migrations.AddField(
            model_name='rsentity',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.RSProduct'),
        ),
        migrations.AddField(
            model_name='rsentity',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.RSStore'),
        ),
    ]
