# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='latest_association_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entity',
            name='latest_association_date',
            field=models.DateTimeField(null=True),
        ),
    ]
