# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0002_auto_20171030_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityhistory',
            options={'ordering': ['entity', 'timestamp'], 'permissions': [('view_stocks', 'Adds the stock field in EntityHistory API')]},
        ),
    ]
