# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0002_auto_20170712_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(),
        ),
    ]
