# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0003_auto_20171102_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityhistory',
            options={'ordering': ['entity', 'timestamp']},
        ),
    ]
