# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0004_auto_20170713_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhistory',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entityhistory',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
