# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0005_auto_20170714_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='latest_registry',
            new_name='active_registry',
        ),
    ]
