# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0005_auto_20171108_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhistory',
            name='cell_monthly_payment',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entityhistory',
            name='normal_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entityhistory',
            name='offer_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
    ]
