# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0007_auto_20171113_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
                'permissions': (('view_visits_user_data', 'Can view the IP and user associated to all visits'), ('backend_list_visits', 'Can view list of visits in the backend')),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['view_category_stocks', 'Can view the category entities stock (also requires store permissions)'], ['is_category_staff', 'Is staff of the category (may also require other permissions)'], ['update_category_pricing', "Can update the pricing of the category's entities"], ['view_category_leads', 'View the leads associated to this category'], ['view_category_visits', 'View the visits associated to this category'], ('backend_list_categories', 'View category list in backend'))},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('name',), 'permissions': [('view_website', 'Can view the website'), ('view_website_visits', 'Can view the visits associated to this website'), ('view_website_leads', 'Can view the leads associated to this website')]},
        ),
        migrations.AddField(
            model_name='visit',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Website'),
        ),
    ]
