# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0007_storeupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeupdatelog',
            name='use_async',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='storeupdatelog',
            name='discovery_url_concurrency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeupdatelog',
            name='products_for_url_concurrency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeupdatelog',
            name='registry_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(default_acl='private'), upload_to='logs/scrapings'),
        ),
        migrations.AlterField(
            model_name='storeupdatelog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In process'), (3, 'Success'), (4, 'Error')], default=1),
        ),
    ]
