# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0008_auto_20171114_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('-timestamp',), 'permissions': (('view_leads_user_data', 'Can view the IP and user associated to all leads'), ('backend_list_leads', 'Can view list of leads in the backend'))},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-timestamp',), 'permissions': (('view_visits_user_data', 'Can view the IP and user associated to all visits'), ('backend_list_visits', 'Can view list of visits in the backend'))},
        ),
    ]
