# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0008_auto_20170715_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeupdatelog',
            name='queue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
