# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0009_storeupdatelog_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeupdatelog',
            name='available_products_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeupdatelog',
            name='discovery_urls_without_products_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeupdatelog',
            name='unavailable_products_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
