# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0009_auto_20171114_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('creation_date',), 'permissions': [('backend_list_entities', 'Can view entity list in backend'), ('backend_view_entity_conflicts', 'Can view entity conflicts in backend'), ('backend_view_entity_estimated_sales', 'Can view the entity estimated sales interface in backend'), ('backend_view_pending_entities', 'Can view the pending entities interface in the backend')]},
        ),
        migrations.AlterModelOptions(
            name='entitylog',
            options={'ordering': ('entity', '-creation_date')},
        ),
    ]
