# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0010_auto_20171205_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solotodouser',
            options={'ordering': ('-date_joined',), 'permissions': (('view_users', 'Can view all users'), ('view_users_with_staff_actions', 'Can view users with that have executed staff actions'), ('backend_list_users', 'Can view user list in backend')), 'verbose_name': 'SoloTodo User', 'verbose_name_plural': 'SoloTodo Users'},
        ),
    ]
