# Generated by Django 2.0 on 2018-01-10 19:02

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0011_auto_20171206_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(default='dummy.jpg', upload_to='store_logos'),
            preserve_default=False,
        ),
    ]
