# Generated by Django 2.0 on 2018-01-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0012_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
