# Generated by Django 2.0 on 2018-01-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0013_auto_20180110_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
