# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0013_auto_20170725_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='decimal_separator',
            field=models.CharField(default=',', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='thousands_separator',
            field=models.CharField(default='.', max_length=10),
            preserve_default=False,
        ),
    ]
