# Generated by Django 2.0 on 2018-01-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0014_auto_20180111_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='solotodouser',
            name='preferred_stores',
            field=models.ManyToManyField(related_name='_solotodouser_preferred_stores_+', to='solotodo.Store'),
        ),
        migrations.AlterField(
            model_name='solotodouser',
            name='preferred_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solotodo.Store'),
        ),
    ]
