# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:39
from __future__ import unicode_literals

from django.db import migrations, models

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    StoreType = apps.get_model("solotodo", "StoreType")
    db_alias = schema_editor.connection.alias
    StoreType.objects.using(db_alias).bulk_create([
        StoreType(name="Retailer"),
        StoreType(name="Wholesaler"),
        StoreType(name="Mobile network operator"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0014_auto_20170726_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(forwards_func),
    ]
