# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0016_auto_20170727_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view store'], ['backend_list_stores', 'Can access store list in backend'])},
        ),
    ]
