# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0017_auto_20170727_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
    ]
