# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0019_auto_20170730_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view store'], ['update_store_prices', 'Can update store'], ['backend_list_stores', 'Can access store list in backend'])},
        ),
    ]
