# Generated by Django 2.0.3 on 2018-03-19 11:49

from django.db import migrations, models
import solotodo_core.s3utils


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0019_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='purchase_proof',
            field=models.FileField(storage=solotodo_core.s3utils.MediaRootPrivateS3Boto3Storage(), upload_to='ratings'),
        ),
    ]
