# Generated by Django 2.0.3 on 2018-03-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0020_auto_20180319_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-pk'], 'permissions': [('view_pending_ratings', 'Can view the ratings pending for approval'), ('is_ratings_staff', 'Has staff permissions over all the ratings'), ('backend_list_ratings', 'View rating list in backend')]},
        ),
    ]
