# Generated by Django 2.0.3 on 2018-04-05 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0021_auto_20180319_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='solotodouser',
            name='preferred_stores_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='last_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
