# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0021_auto_20170806_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view store'], ['view_store_update_logs', 'Can view store update logs'], ['update_store_prices', 'Can update store'], ['backend_view_store', 'Can view store list and detail in backend'])},
        ),
    ]
