# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0022_auto_20170807_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='discovery_url',
            field=models.URLField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='entity',
            name='url',
            field=models.URLField(db_index=True, max_length=512),
        ),
    ]
