# Generated by Django 2.0.3 on 2018-04-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0022_auto_20180405_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
    ]
