# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0015_auto_20160328_1727'),
        ('solotodo', '0024_producttypetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='detail_bucket_key_fields',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='meta_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metamodel.MetaModel'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='search_bucket_key_fields',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='similar_products_fields',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='suggested_alternatives_filter',
            field=models.CharField(default='{}', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='suggested_alternatives_ordering',
            field=models.CharField(default='price', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solotodo.ProductTypeTier'),
            preserve_default=False,
        ),
    ]
