# Generated by Django 2.0.3 on 2018-04-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0025_auto_20180406_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['is_category_staff', 'Is staff of the category'], ['view_category_leads', 'View the leads associated to this category'], ['view_category_visits', 'View the visits associated to this category'], ['view_category_reports', 'Download the reports associated to this category'], ['backend_list_categories', 'View category list in backend'])},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view the store'], ['view_store_update_logs', 'Can view the store update logs'], ['view_store_stocks', 'Can view the store entities stock'], ['update_store_pricing', 'Can update the store pricing'], ['view_store_leads', 'View the leads associated to this store'], ['view_store_reports', 'Download the reports associated to this store'], ['backend_list_stores', 'Can view store list in backend'])},
        ),
    ]
