# Generated by Django 2.0.3 on 2018-05-17 16:19

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0027_materializedentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', sorl.thumbnail.fields.ImageField(upload_to='product_pictures')),
                ('ordering', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='solotodo.Product')),
            ],
            options={
                'ordering': ('product', 'ordering'),
            },
        ),
    ]
