# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0027_auto_20170810_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='part_number',
        ),
    ]
