# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0028_auto_20170810_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('instance_model',)},
        ),
    ]
