# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0029_auto_20170810_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'permissions': (['view_entities', 'Can view related entities'],)},
        ),
    ]
