# Generated by Django 2.0.3 on 2019-01-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0029_entityhistory_estimated_sales_since_previous_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='cell_plan_name',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
    ]
