# Generated by Django 2.0.3 on 2019-01-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0030_auto_20190109_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitylog',
            name='cell_plan_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
