# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0031_auto_20170811_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view store'], ['view_store_update_logs', 'Can view store update logs'], ['view_store_entities', 'Can view entities of the store'], ['update_store_prices', 'Can update store prices'], ['backend_view_store', 'Can view store list and detail in backend'])},
        ),
    ]
