# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0032_auto_20170814_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'permissions': (['view_product_type_entities', 'Can view entities associated to this product type'],)},
        ),
    ]
