# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    NumberFormatting = apps.get_model("solotodo", "NumberFormatting")
    db_alias = schema_editor.connection.alias
    NumberFormatting.objects.using(db_alias).bulk_create([
        NumberFormatting(thousands_separator=".", decimal_separator=","),
        NumberFormatting(thousands_separator=",", decimal_separator="."),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0034_entityhistory_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberFormatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thousands_separator', models.CharField(max_length=3)),
                ('decimal_separator', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'permissions': (['view_product_type_entities', 'Can view entities associated to this product type'], ['view_product_type_products', 'Can view products associated to this product type'])},
        ),
        migrations.AlterField(
            model_name='entity',
            name='latest_association_date',
            field=models.DateTimeField(blank=True, null=True),
        ),

        migrations.RunPython(forwards_func),
    ]
