# Generated by Django 2.0.3 on 2019-02-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_bannerasset_creation_date'),
        ('solotodo', '0034_auto_20190214_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='active_banner_update',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='banners.BannerUpdate'),
        ),
    ]
