# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0035_auto_20170816_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='number_formating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solotodo.NumberFormatting'),
            preserve_default=False,
        ),
    ]
