# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0036_country_number_formating'),
    ]

    operations = [
        migrations.AddField(
            model_name='solotodouser',
            name='preferred_number_formating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.NumberFormatting'),
        ),
    ]
