# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0037_solotodouser_preferred_number_formating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumberFormatting',
            new_name='NumberFormat',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='number_formating',
            new_name='number_format',
        ),
        migrations.RenameField(
            model_name='solotodouser',
            old_name='preferred_number_formating',
            new_name='preferred_number_format',
        ),
    ]
