# Generated by Django 2.0.3 on 2019-04-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0037_auto_20190311_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['is_category_staff', 'Is staff of the category'], ['view_category_leads', 'View the leads associated to this category'], ['view_category_visits', 'View the visits associated to this category'], ['view_category_reports', 'Download the reports associated to this category'], ['view_category_share_of_shelves', 'View share of shelves of the category'], ['create_category_product_list', 'Can create a product list in this category'], ['create_category_brand_comparison', 'Can create a brand comparison in this category'], ['backend_list_categories', 'View category list in backend'])},
        ),
    ]
