# Generated by Django 2.0.3 on 2019-04-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0037_auto_20190311_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Brand'),
            preserve_default=False,
        ),
    ]
