# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0038_auto_20170816_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberformat',
            name='name',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
    ]
