# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0040_auto_20170816_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='picture_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
