# Generated by Django 2.0.3 on 2019-04-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0040_auto_20190409_1844'),
        ('solotodo', '0039_auto_20190403_1457'),
    ]

    operations = [
    ]
