# Generated by Django 2.0.3 on 2019-04-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0041_merge_20190410_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['is_category_staff', 'Is staff of the category'], ['view_category_leads', 'View the leads associated to this category'], ['view_category_visits', 'View the visits associated to this category'], ['view_category_reports', 'Download the reports associated to this category'], ['view_category_share_of_shelves', 'View share of shelves of the category'], ['create_category_product_list', 'Can create a product list in this category'], ['create_category_brand_comparison', 'Can create a brand comparison for this category'], ['backend_list_categories', 'View category list in backend'], ['view_category_entity_positions', 'Can view category entity positions'])},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view the store'], ['view_store_update_logs', 'Can view the store update logs'], ['view_store_stocks', 'Can view the store entities stock'], ['update_store_pricing', 'Can update the store pricing'], ['view_store_leads', 'View the leads associated to this store'], ['view_store_reports', 'Download the reports associated to this store'], ['backend_list_stores', 'Can view store list in backend'], ['view_store_banners', 'Can view store banners'], ['view_store_entity_positions', 'Can view store entity positions'])},
        ),
    ]
