# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0042_auto_20170822_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'permissions': (['view_product_type_entities', 'Can view entities associated to this product type'], ['view_product_type_products', 'Can view products associated to this product type'], ['associate_product_type_entities', 'Can associate product type entities'], ['update_product_type_entities_prices', 'Can update product type entities prices'])},
        ),
    ]
