# Generated by Django 2.0.3 on 2019-04-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0042_auto_20190415_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitySectionPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('entity_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.EntityHistory')),
            ],
            options={
                'ordering': ('entity_history', 'section', 'value'),
            },
        ),
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Store')),
            ],
            options={
                'ordering': ('store', 'name'),
            },
        ),
        migrations.AddField(
            model_name='entitysectionposition',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.StoreSection'),
        ),
    ]
