# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0043_auto_20170823_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'permissions': (['view_product_type_entities', 'Can view entities associated to this product type'], ['view_product_type_products', 'Can view products associated to this product type'], ['associate_product_type_entities', 'Can associate product type entities'], ['update_product_type_entities_pricing', 'Can update product type entities prices'])},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view store'], ['view_store_update_logs', 'Can view store update logs'], ['view_store_entities', 'Can view entities of the store'], ['update_store_pricing', 'Can update store pricing'], ['associate_store_entities', 'Can associate store entities'], ['backend_view_store', 'Can view store list and detail in backend'])},
        ),
    ]
