# Generated by Django 2.0.3 on 2019-04-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0043_auto_20190417_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesection',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='solotodo.Store'),
        ),
    ]
