# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0044_auto_20170824_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('cell_plan_name', models.CharField(max_length=50, null=True)),
                ('part_number', models.CharField(max_length=50, null=True)),
                ('sku', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(max_length=512, null=True)),
                ('discovery_url', models.URLField(max_length=512, null=True)),
                ('picture_url', models.URLField(max_length=512, null=True)),
                ('description', models.TextField(null=True)),
                ('is_visible', models.NullBooleanField()),
                ('cell_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solotodo.Product')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Currency')),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Entity'),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Product'),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.ProductType'),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='scraped_product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solotodo.ProductType'),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
