# Generated by Django 2.0.3 on 2019-04-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0044_auto_20190418_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storesection',
            unique_together={('store', 'name')},
        ),
    ]
