# Generated by Django 2.0.3 on 2019-04-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0045_auto_20190418_1329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitysectionposition',
            unique_together={('entity_history', 'section')},
        ),
    ]
