# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0046_auto_20170824_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitylog',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Currency'),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='discovery_url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='is_visible',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.ProductType'),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='scraped_product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solotodo.ProductType'),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
