# Generated by Django 2.0.3 on 2019-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0047_auto_20190515_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='flixmedia_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='video_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='flixmedia_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='video_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
