# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0047_auto_20170824_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityhistory',
            options={'ordering': ['entity', 'timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='entityhistory',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='entityhistory',
            name='date',
        ),
    ]
