# Generated by Django 2.0.3 on 2019-06-25 15:57

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0048_auto_20190610_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpicture',
            name='file',
            field=sorl.thumbnail.fields.ImageField(max_length=512, upload_to='product_pictures'),
        ),
    ]
