# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0048_auto_20170826_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
