# Generated by Django 2.0.3 on 2019-06-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0049_auto_20190625_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='review_avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='review_avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
