# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0050_auto_20170830_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProductTypeTier',
            new_name='CategoryTier',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category_entities', 'Can view entities associated to this category (also requires store permissions)'], ['view_category_products', 'Can view products associated to this category'], ['category_entities_staff', 'Is staff of the entities of this category (also requires store permissions)'], ['update_category_entities_pricing', "Can update the pricing of this category's entities"])},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view store'], ['view_store_update_logs', 'Can view store update logs'], ['view_store_entities', 'Can view entities of this store (also requires category permissions)'], ['update_store_pricing', 'Can update store pricing'], ['store_entities_staff', 'Is staff of the entities of this store (also requires category permissions)'], ['backend_view_store', 'Can view store list and detail in backend'])},
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='product_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='scraped_product_type',
            new_name='scraped_category',
        ),
        migrations.RenameField(
            model_name='entitylog',
            old_name='product_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='entitylog',
            old_name='scraped_product_type',
            new_name='scraped_category',
        ),
        migrations.RenameField(
            model_name='storeupdatelog',
            old_name='product_types',
            new_name='categories',
        ),
    ]
