# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0051_auto_20170831_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeupdatelog',
            name='queue',
        ),
    ]
