# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0052_remove_storeupdatelog_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='latest_staff_access_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='latest_staff_access_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
