# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0053_auto_20170901_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='latest_association_date',
            new_name='last_association_date',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='latest_association_user',
            new_name='last_association_user',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='latest_staff_access_date',
            new_name='last_staff_access_date',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='latest_staff_access_user',
            new_name='last_staff_access_user',
        ),
    ]
