# Generated by Django 2.0.3 on 2019-07-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0053_remove_entityhistory_estimated_sales_since_previous_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityhistory',
            name='picture_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='review_avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='video_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
