# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0054_auto_20170901_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
