# Generated by Django 2.0.3 on 2019-07-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0055_lead_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True),
        ),
    ]
