# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0055_auto_20170902_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='last_pricing_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
