# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 02:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0056_entity_last_pricing_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='last_pricing_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 2, 19, 41, 660237, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
