# Generated by Django 2.0.3 on 2019-07-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('solotodo', '0057_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_store', to='auth.Group'),
        ),
    ]
