# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0057_auto_20170902_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('storescraper_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
