# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0059_entity_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitylog',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solotodo.EntityState'),
            preserve_default=False,
        ),
    ]
