# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0060_entitylog_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='last_staff_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
