# Generated by Django 2.0.3 on 2019-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0061_auto_20190821_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solotodouser',
            name='preferred_store',
        ),
        migrations.AddField(
            model_name='solotodouser',
            name='preferred_exclude_refurbished',
            field=models.BooleanField(default=False),
        ),
    ]
