# Generated by Django 2.0.3 on 2020-04-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0062_auto_20190906_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='seller',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
