# Generated by Django 2.0.3 on 2020-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0063_entity_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
