# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0063_entity_last_pricing_update_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='last_pricing_update_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
