# Generated by Django 2.2.13 on 2020-08-17 21:04

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0064_product_part_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterializedEntity',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['is_category_staff', 'Is staff of the category'], ['view_category_leads', 'View the leads associated to this category'], ['view_category_visits', 'View the visits associated to this category'], ['view_category_reports', 'Download the reports associated to this category'], ['view_category_share_of_shelves', 'View share of shelves of the category'], ['create_category_product_list', 'Can create a product list in this category'], ['create_category_brand_comparison', 'Can create a brand comparison for this category'], ['backend_list_categories', 'View category list in backend'], ['view_category_entity_positions', 'Can view category entity positions'], ['create_category_keyword_search', 'Can create keyword searches in this category'])},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store_update_logs', 'Can view the store update logs'], ['view_store_stocks', 'Can view the store entities stock'], ['update_store_pricing', 'Can update the store pricing'], ['view_store_leads', 'View the leads associated to this store'], ['view_store_reports', 'Download the reports associated to this store'], ['backend_list_stores', 'Can view store list in backend'], ['view_store_banners', 'Can view store banners'], ['view_store_entity_positions', 'Can view store entity positions'], ['create_store_keyword_search', 'Can create keyword searches in this store'])},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('name',), 'permissions': [('view_website_visits', 'Can view the visits associated to this website'), ('view_website_leads', 'Can view the leads associated to this website')]},
        ),
        migrations.AlterField(
            model_name='solotodouser',
            name='preferred_exclude_refurbished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='storeupdatelog',
            name='registry_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(custom_domain=None, default_acl='private'), upload_to='logs/scrapings'),
        ),
    ]
