# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0064_auto_20170904_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='last_association_date',
            new_name='last_association',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='last_staff_access_date',
            new_name='last_staff_access',
        ),
    ]
