# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0067_auto_20170909_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solotodouser',
            options={'ordering': ('-date_joined',), 'permissions': (('view_users', 'Can view all users'), ('view_users_with_staff_actions', 'Can view users with that have executed staff actions')), 'verbose_name': 'SoloTodo User', 'verbose_name_plural': 'SoloTodo Users'},
        ),
    ]
