# Generated by Django 2.2.13 on 2021-12-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0067_auto_20210719_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Bundle'),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Bundle'),
        ),
    ]
