# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0068_auto_20170909_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('instance_model',), 'permissions': [('backend_list_product', 'Can view product list in backend')]},
        ),
    ]
