# Generated by Django 2.2.13 on 2022-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0068_auto_20211226_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='email_or_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
