# Generated by Django 2.2.13 on 2022-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0069_rating_email_or_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
