# Generated by Django 2.2.13 on 2022-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0070_category_short_description_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='browse_result_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='detail_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
