# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0070_auto_20170911_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='picture_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
