# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0071_auto_20170913_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='picture_url',
            new_name='picture_urls',
        ),
    ]
