# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0072_auto_20170913_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitylog',
            name='picture_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
