# Generated by Django 2.2.13 on 2022-10-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0072_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='best_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='solotodo.Coupon'),
        ),
    ]
