# Generated by Django 2.2.13 on 2022-10-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0073_entity_best_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='SOLOTODO', max_length=100),
            preserve_default=False,
        ),
    ]
