# Generated by Django 2.2.13 on 2022-10-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0074_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, to='solotodo.Category'),
        ),
    ]
