# Generated by Django 2.2.13 on 2022-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0075_coupon_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='seller',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
