# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0075_auto_20170913_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['view_category_entities', 'Can view entities associated to this category (also requires store permissions)'], ['view_category_products', 'Can view products associated to this category'], ['category_entities_staff', 'Is staff of the entities of this category (also requires store permissions)'], ['update_category_entities_pricing', "Can update the pricing of this category's entities"], ['backend_view_category', 'Can view category list / detail in the backend'])},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view the store'], ['view_store_update_logs', 'Can view store update logs'], ['view_store_entities', 'Can view entities of this store (also requires category permissions)'], ['update_store_pricing', 'Can update store pricing'], ['store_entities_staff', 'Is staff of the entities of this store (also requires category permissions)'], ['backend_view_store', 'Can view store list and detail in backend'])},
        ),
    ]
