# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0078_auto_20170914_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view the store'], ['backend_view_store', 'Can view store list in backend'], ['view_store_update_logs', 'Can view store update logs'], ['update_store_pricing', 'Can update store pricing'], ['store_entities_staff', 'Is staff of the entities of this store (also requires category permissions)'])},
        ),
    ]
