# Generated by Django 3.2.19 on 2023-06-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0078_auto_20230606_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='has_virtual_assistant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='has_virtual_assistant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeupdatelog',
            name='use_async',
            field=models.BooleanField(null=True),
        ),
    ]
