# Generated by Django 3.2.19 on 2023-06-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0079_auto_20230606_2108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitysectionposition',
            unique_together=set(),
        ),
    ]
