# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0079_auto_20170914_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view the store'], ['view_store_update_logs', 'Can view the store update logs'], ['update_store_pricing', 'Can update the store pricing'], ['is_store_staff', 'Is staff of the store (may require additional permissions)'], ['backend_list_stores', 'Can view store list in backend'])},
        ),
    ]
