# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0080_auto_20170914_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['is_category_staff', 'Is staff of the category (may also require other permissions)'], ['update_category_pricing', "Can update the pricing of the category's entities"])},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'permissions': [('backend_list_entities', 'Can view entity list in backend')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('instance_model',), 'permissions': [('backend_list_products', 'Can view product list in backend')]},
        ),
    ]
