# Generated by Django 4.2.3 on 2023-07-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0080_alter_entitysectionposition_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solotodouser',
            name='preferred_stores',
            field=models.ManyToManyField(blank=True, related_name='+', to='solotodo.store'),
        ),
    ]
