# Generated by Django 4.2.3 on 2023-09-11 15:49

from django.db import migrations, models
import solotodo.utils


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0082_rating_last_updated_rating_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store_update_logs', 'Can view the store update logs'], ['view_store_stocks', 'Can view the store entities stock'], ['update_store_pricing', 'Can update the store pricing'], ['view_store_leads', 'View the leads associated to this store'], ['view_store_reports', 'Download the reports associated to this store'], ['backend_list_stores', 'Can view store list in backend'], ['view_store_banners', 'Can view store banners'], ['view_store_entity_positions', 'Can view store entity positions'], ['create_store_keyword_search', 'Can create keyword searches in this store'], ['view_store_sii_details', 'Can view the SII details for the store'])},
        ),
        migrations.AddField(
            model_name='store',
            name='sii_razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sii_rut',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[solotodo.utils.validate_sii_rut]),
        ),
    ]
