# Generated by Django 5.0 on 2023-12-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0085_alter_entity_sec_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='entities',
            field=models.ManyToManyField(blank=True, to='solotodo.entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='best_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_with_coupon', to='solotodo.coupon'),
        ),
    ]
