# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0085_storevisit_api_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreVisit',
            new_name='EntityVisit',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['view_category_stocks', 'Can view the category entities stock (also requires store permissions)'], ['is_category_staff', 'Is staff of the category (may also require other permissions)'], ['update_category_pricing', "Can update the pricing of the category's entities"], ['view_category_entity_visits', 'View the entity visits associated to this category'])},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view the store'], ['view_store_update_logs', 'Can view the store update logs'], ['view_store_stocks', 'Can view the store entities stock (also requires category permissions)'], ['update_store_pricing', 'Can update the store pricing'], ['is_store_staff', 'Is staff of the store (may require additional permissions)'], ['backend_list_stores', 'Can view store list in backend'], ('view_store_entity_visits', 'View the entity visits associated to this store'))},
        ),
    ]
