# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0086_auto_20170925_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view the store'], ['view_store_update_logs', 'Can view the store update logs'], ['view_store_stocks', 'Can view the store entities stock (also requires category permissions)'], ['update_store_pricing', 'Can update the store pricing'], ['is_store_staff', 'Is staff of the store (may require additional permissions)'], ('view_store_entity_visits', 'View the entity visits associated to this store'), ['backend_list_stores', 'Can view store list in backend'])},
        ),
        migrations.AddField(
            model_name='solotodouser',
            name='preferred_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Store'),
        ),
    ]
