# Generated by Django 5.1.1 on 2024-09-13 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0086_coupon_entities_alter_entity_best_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFieldWatcher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("es_label_path", models.CharField(max_length=255)),
                ("es_value_path", models.CharField(max_length=255)),
                ("es_instance_model_id_path", models.CharField(max_length=255)),
                ("es_target_value", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solotodo.category",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "name"),
            },
        ),
    ]
