# Generated by Django 5.1.1 on 2024-10-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solotodo", "0087_productfieldwatcher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solotodouser",
            options={
                "ordering": ("-date_joined",),
                "permissions": (
                    ("view_users", "Can view all users"),
                    (
                        "view_users_with_staff_actions",
                        "Can view users with that have executed staff actions",
                    ),
                    ("backend_list_users", "Can view user list in backend"),
                    ("is_staff_manager", "Is manager of staff users"),
                ),
                "verbose_name": "SoloTodo User",
                "verbose_name_plural": "SoloTodo Users",
            },
        ),
    ]
