# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0087_auto_20170925_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('creation_date',), 'permissions': [('backend_list_entities', 'Can view entity list in backend'), ('backend_view_entity_conflicts', 'Can view entity conflicts in backend')]},
        ),
    ]
