# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0088_auto_20170930_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityVisit',
            new_name='Lead',
        ),
    ]
