# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0089_auto_20170930_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiclient',
            options={'ordering': ('name',), 'permissions': [('view_api_client_leads', 'View the leads associated to this API client')]},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['view_category_stocks', 'Can view the category entities stock (also requires store permissions)'], ['is_category_staff', 'Is staff of the category (may also require other permissions)'], ['update_category_pricing', "Can update the pricing of the category's entities"], ['view_category_leads', 'View the leads associated to this category'])},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('entity_history', 'timestamp'), 'permissions': (('backend_list_leads', 'Can view list of leads in the backend'),)},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'permissions': (['view_store', 'Can view the store'], ['view_store_update_logs', 'Can view the store update logs'], ['view_store_stocks', 'Can view the store entities stock (also requires category permissions)'], ['update_store_pricing', 'Can update the store pricing'], ['is_store_staff', 'Is staff of the store (may require additional permissions)'], ('view_store_leads', 'View the leads associated to this store'), ['backend_list_stores', 'Can view store list in backend'])},
        ),
    ]
