# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 14:27
from __future__ import unicode_literals

from django.db import migrations
import gtin_fields.fields
import gtin_fields.validators


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0090_auto_20170930_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='ean',
            field=gtin_fields.fields.EAN13Field(blank=True, max_length=13, null=True, validators=[gtin_fields.validators._EAN13Validator()], verbose_name='EAN-13'),
        ),
        migrations.AddField(
            model_name='entitylog',
            name='ean',
            field=gtin_fields.fields.EAN13Field(blank=True, max_length=13, null=True, validators=[gtin_fields.validators._EAN13Validator()], verbose_name='EAN-13'),
        ),
    ]
