# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0091_auto_20171001_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitystate',
            name='storescraper_name',
            field=models.URLField(),
        ),
    ]
