# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0092_auto_20171001_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='condition',
            field=models.URLField(choices=[('https://schema.org/DamagedCondition', 'Damaged'), ('https://schema.org/NewCondition', 'New'), ('https://schema.org/RefurbishedCondition', 'Refurbished'), ('https://schema.org/UsedCondition', 'Used')], default='https://schema.org/NewCondition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entitylog',
            name='condition',
            field=models.URLField(choices=[('https://schema.org/DamagedCondition', 'Damaged'), ('https://schema.org/NewCondition', 'New'), ('https://schema.org/RefurbishedCondition', 'Refurbished'), ('https://schema.org/UsedCondition', 'Used')], default='https://schema.org/NewCondition'),
            preserve_default=False,
        ),
    ]
