# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0093_auto_20171001_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='state',
        ),
        migrations.RemoveField(
            model_name='entitylog',
            name='state',
        ),
        migrations.DeleteModel(
            name='EntityState',
        ),
    ]
