# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0095_auto_20171003_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('creation_date',), 'permissions': [('backend_list_entities', 'Can view entity list in backend'), ('backend_view_entity_conflicts', 'Can view entity conflicts in backend'), ('backend_view_entity_estimated_sales', 'Can view the entity estiamted sales interface in backend')]},
        ),
    ]
