# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0016_auto_20170920_2002'),
        ('solotodo', '0096_auto_20171003_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecsField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('exact', 'Exact'), ('lte', 'Less than or equal'), ('gte', 'Greater than or equal'), ('range', 'Range (from / to)')], max_length=20)),
                ('es_base_path', models.CharField(max_length=100)),
                ('es_value_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('es_label_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
                ('meta_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamodel.MetaModel')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
    ]
