# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0097_categoryspecsfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryspecsfield',
            old_name='es_base_path',
            new_name='es_field',
        ),
        migrations.RenameField(
            model_name='categoryspecsfield',
            old_name='es_label_suffix',
            new_name='value_field',
        ),
        migrations.RemoveField(
            model_name='categoryspecsfield',
            name='es_value_suffix',
        ),
        migrations.AlterField(
            model_name='categoryspecsfield',
            name='type',
            field=models.CharField(choices=[('exact', 'Exact'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal'), ('range', 'Range (from / to)')], max_length=20),
        ),
    ]
