# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0098_auto_20171006_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryspecsfield',
            name='es_ordering_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
