# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0099_categoryspecsfield_es_ordering_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryspecsfield',
            name='es_ordering_field',
        ),
    ]
