# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0100_remove_categoryspecsfield_es_ordering_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorySpecsField',
            new_name='CategorySpecsFilter',
        ),
    ]
