# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0101_auto_20171007_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('es_field', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
    ]
