# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0102_categoryspecsorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solotodouser',
            name='preferred_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Country'),
            preserve_default=False,
        ),
    ]
