# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0103_auto_20171011_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (['view_category', 'Can view the category'], ['view_category_stocks', 'Can view the category entities stock (also requires store permissions)'], ['is_category_staff', 'Is staff of the category (may also require other permissions)'], ['update_category_pricing', "Can update the pricing of the category's entities"], ['view_category_leads', 'View the leads associated to this category'], ('backend_list_categories', 'View category list in backend'))},
        ),
    ]
