# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0104_auto_20171013_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solotodouser',
            name='preferred_store',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Store'),
        ),
    ]
