# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0105_auto_20171016_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solotodouser',
            name='preferred_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Country'),
        ),
        migrations.AlterField(
            model_name='solotodouser',
            name='preferred_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Store'),
        ),
    ]
