# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0013_auto_20160120_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metafield',
            options={'ordering': ('parent', 'ordering', 'pk')},
        ),
    ]
