# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0014_auto_20160229_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancefield',
            options={'ordering': ('parent', 'field', 'value')},
        ),
    ]
