# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0015_auto_20160328_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancemodel',
            options={'ordering': ('decimal_value', 'unicode_value', 'unicode_representation')},
        ),
    ]
