# Generated by Django 2.2.13 on 2021-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0016_auto_20170920_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafield',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
