# Generated by Django 2.2.13 on 2021-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0016_auto_20170920_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancemodel',
            name='decimal_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=5, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='instancemodel',
            name='unicode_representation',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instancemodel',
            name='unicode_value',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
