# Generated by Django 2.2.13 on 2021-10-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0017_metafield_help_text'),
        ('metamodel', '0017_auto_20210405_1621'),
    ]

    operations = [
    ]
