# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0009_auto_20171114_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtbBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefered_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('storescraper_class', models.CharField(blank=True, max_length=100, null=True)),
                ('stores', models.ManyToManyField(to='solotodo.Store')),
            ],
            options={
                'ordering': ('name',),
                'permissions': [('view_wtb_brand', 'Can view the WTB brand'), ('backend_view_wtb', 'Display the WTB menu in the backend')],
            },
        ),
        migrations.CreateModel(
            name='WtbBrandUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In process'), (3, 'Success'), (4, 'Error')], default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('registry_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(default_acl='private'), upload_to='logs/wtb')),
                ('entity_count', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtb.WtbBrand')),
            ],
            options={
                'ordering': ('brand', '-last_updated'),
            },
        ),
        migrations.CreateModel(
            name='WtbEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('picture_url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtb.WtbBrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Product')),
            ],
            options={
                'ordering': ('brand', 'name'),
            },
        ),
    ]
