# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtbbrand',
            old_name='storescraper_class',
            new_name='scraper_class',
        ),
    ]
