# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0002_auto_20171121_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtbbrand',
            old_name='scraper_class',
            new_name='storescraper_class',
        ),
    ]
