# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0003_auto_20171122_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbentity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
