# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wtb', '0004_wtbentity_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbentity',
            name='last_association',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtbentity',
            name='last_association_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
