# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0007_auto_20171123_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wtbentity',
            options={'ordering': ('brand', 'name'), 'permissions': [('backend_view_pending_wtb_entities', 'Can view the pending WTB entities interface in the backend')]},
        ),
    ]
