# Generated by Django 2.0.3 on 2019-07-09 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0009_wtbbrand_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtbentity',
            name='last_association_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
