# Generated by Django 2.0.3 on 2019-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0010_auto_20190709_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtbentity',
            name='key',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
