# Generated by Django 2.0.3 on 2019-08-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0011_auto_20190718_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtbentity',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
