# Generated by Django 2.0.3 on 2019-08-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0012_auto_20190807_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbentity',
            name='model_name',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
