# Generated by Django 2.0.3 on 2020-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0013_wtbentity_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbentity',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
