# Generated by Django 2.0.3 on 2020-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0014_wtbentity_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbentity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
