# Generated by Django 2.2.13 on 2020-08-17 21:04

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0015_wtbentity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtbbrandupdatelog',
            name='registry_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(custom_domain=None, default_acl='private'), upload_to='logs/wtb'),
        ),
    ]
