# Generated by Django 5.0 on 2024-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtb', '0017_wtbentity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtbentity',
            name='picture_url',
            field=models.URLField(max_length=256),
        ),
    ]
