# Generated by Django 2.0.3 on 2019-03-11 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solotodo', '0036_auto_20190220_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
            ],
            options={
                'ordering': ('id',),
                'permissions': (['backend_list_product_lists', 'Can see product lists in the backend'],),
            },
        ),
        migrations.CreateModel(
            name='ProductListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Product')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_lists.ProductList')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.AddField(
            model_name='productlist',
            name='products',
            field=models.ManyToManyField(through='product_lists.ProductListEntry', to='solotodo.Product'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
