# Generated by Django 2.0.3 on 2019-03-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlist',
            options={'ordering': ('-id',), 'permissions': (['backend_list_product_lists', 'Can see product lists in the backend'],)},
        ),
        migrations.AlterModelOptions(
            name='productlistentry',
            options={'ordering': ('product_list', 'ordering')},
        ),
        migrations.AlterField(
            model_name='productlistentry',
            name='product_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='product_lists.ProductList'),
        ),
    ]
