# Generated by Django 2.0.3 on 2019-03-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0037_auto_20190311_1746'),
        ('product_lists', '0002_auto_20190311_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productlistentry',
            unique_together={('product_list', 'product')},
        ),
    ]
