# Generated by Django 2.0.3 on 2019-03-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_lists', '0003_auto_20190312_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
