# Generated by Django 2.0.3 on 2019-10-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_lists', '0004_auto_20190312_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='productlistentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productlistentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productlistentry',
            name='product_list',
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
        migrations.DeleteModel(
            name='ProductListEntry',
        ),
    ]
