# Generated by Django 2.0 on 2018-02-06 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0017_country_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('products_pool', models.ManyToManyField(blank=True, to='solotodo.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Product')),
                ('selected_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Store')),
            ],
            options={
                'ordering': ['budget', 'category'],
            },
        ),
    ]
