# Generated by Django 2.0 on 2018-02-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
