# Generated by Django 2.0 on 2018-02-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0017_country_flag'),
        ('hardware', '0003_auto_20180206_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='selected_product',
        ),
        migrations.RemoveField(
            model_name='budgetentry',
            name='selected_store',
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='selected_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solotodo.Entity'),
        ),
    ]
