# Generated by Django 2.0 on 2018-02-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_auto_20180212_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
