# Generated by Django 2.0.3 on 2019-06-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_budget_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetentry',
            options={'ordering': ['budget', 'category__budget_ordering', 'id']},
        ),
    ]
