# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdownload',
            name='file',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
