# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportdownload_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('name',), 'permissions': (('view_report', 'Can view the report'), ('backend_list_reports', 'Can view report list in backend'))},
        ),
        migrations.AlterField(
            model_name='reportdownload',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(default_acl='private'), upload_to=''),
        ),
    ]
