# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20171127_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='foo'),
            preserve_default=False,
        ),
    ]
