# Generated by Django 2.0.3 on 2019-05-15 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solotodo', '0046_auto_20190418_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=512)),
                ('threshold', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'store', 'category', 'keyword'),
            },
        ),
        migrations.CreateModel(
            name='KeywordSearchEntityPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Entity')),
            ],
            options={
                'ordering': ('entity', 'update', 'value'),
            },
        ),
        migrations.CreateModel(
            name='KeywordSearchUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=512)),
                ('creation_date', models.DateTimeField()),
                ('status', models.CharField(max_length=512)),
                ('message', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ('search',),
            },
        ),
        migrations.AddField(
            model_name='keywordsearchentityposition',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyword_search_positions.KeywordSearchUpdate'),
        ),
    ]
