# Generated by Django 2.0.3 on 2019-05-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_search_positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordsearch',
            options={'ordering': ('user', 'store', 'category', 'keyword'), 'permissions': (['backend_list_keyword_searches', 'Can see keyword searches in the backend'],)},
        ),
        migrations.AlterField(
            model_name='keywordsearchupdate',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyword_search_positions.KeywordSearch'),
        ),
    ]
