# Generated by Django 2.0.3 on 2019-05-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_search_positions', '0002_auto_20190515_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsearch',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keywordsearchupdate',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keywordsearchupdate',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keywordsearchupdate',
            name='status',
            field=models.IntegerField(choices=[(1, 'In process'), (2, 'Success'), (3, 'Error')], default=1),
        ),
    ]
