# Generated by Django 2.0.3 on 2019-05-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_search_positions', '0003_auto_20190516_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordsearch',
            options={'ordering': ('-creation_date',), 'permissions': (['backend_list_keyword_searches', 'Can see keyword searches in the backend'],)},
        ),
    ]
