# Generated by Django 2.0.3 on 2019-05-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_search_positions', '0004_auto_20190517_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsearch',
            name='active_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyword_search_positions.KeywordSearchUpdate'),
        ),
    ]
