# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_columns', '0002_auto_20171124_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycolumn',
            options={'ordering': ('field__category', 'purpose', 'ordering')},
        ),
    ]
