# Generated by Django 2.0.3 on 2019-10-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_columns', '0003_auto_20171127_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycolumn',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
    ]
