# Generated by Django 2.0.3 on 2018-09-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0029_entityhistory_estimated_sales_since_previous_registry'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotification',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.Alert'),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('product', 'email')},
        ),
    ]
