# Generated by Django 2.0.3 on 2019-02-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20180912_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.Alert')),
            ],
            options={
                'ordering': ('alert',),
            },
        ),
    ]
