# Generated by Django 2.0.3 on 2019-02-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_anonymousalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousalert',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alerts.Alert'),
        ),
    ]
