# Generated by Django 2.0.3 on 2019-02-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20190206_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Product'),
        ),
    ]
