# Generated by Django 2.0.3 on 2019-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0059_entity_scraped_condition'),
        ('alerts', '0010_auto_20190809_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricealerthistory',
            name='entries',
            field=models.ManyToManyField(blank=True, to='solotodo.EntityHistory'),
        ),
    ]
