# Generated by Django 2.0.3 on 2019-09-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_productpricealerthistory_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='normal_price_registry',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='offer_price_registry',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='product',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='alertnotification',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='alertnotification',
            name='previous_normal_price_registry',
        ),
        migrations.RemoveField(
            model_name='alertnotification',
            name='previous_offer_price_registry',
        ),
        migrations.RemoveField(
            model_name='anonymousalert',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='useralert',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='useralert',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='useralert',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertNotification',
        ),
        migrations.DeleteModel(
            name='AnonymousAlert',
        ),
        migrations.DeleteModel(
            name='UserAlert',
        ),
    ]
