# Generated by Django 2.0.3 on 2019-04-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0041_merge_20190410_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('entity_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.EntityHistory')),
            ],
            options={
                'ordering': ('entity_history', 'section', 'value'),
            },
        ),
        migrations.CreateModel(
            name='EntityPositionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Store')),
            ],
            options={
                'ordering': ('store', 'name'),
            },
        ),
        migrations.AddField(
            model_name='entityposition',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_positions.EntityPositionSection'),
        ),
    ]
