# Generated by Django 2.0.3 on 2019-04-03 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solotodo', '0039_auto_20190403_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('price_type', models.CharField(choices=[('normal', 'Normal'), ('offer', 'Offer')], default='offer', max_length=512)),
                ('brand_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solotodo.Brand')),
                ('brand_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solotodo.Brand')),
                ('stores', models.ManyToManyField(to='solotodo.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'name'),
                'permissions': (['backend_list_brand_comparisons', 'Can see brand comparisons in the backend'],),
            },
        ),
        migrations.CreateModel(
            name='BrandComparisonSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('ordering', models.IntegerField()),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='brand_comparisons.BrandComparison')),
            ],
            options={
                'ordering': ('comparison', 'ordering'),
            },
        ),
        migrations.CreateModel(
            name='BrandComparisonSegmentRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('product_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='solotodo.Product')),
                ('product_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='solotodo.Product')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='brand_comparisons.BrandComparisonSegment')),
            ],
            options={
                'ordering': ('segment', 'ordering'),
            },
        ),
    ]
