# Generated by Django 2.0.3 on 2019-04-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0039_auto_20190403_1457'),
        ('brand_comparisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcomparison',
            name='category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category'),
            preserve_default=False,
        ),
    ]
