# Generated by Django 2.0.3 on 2019-04-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_comparisons', '0002_brandcomparison_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandcomparisonsegment',
            unique_together={('comparison', 'ordering')},
        ),
    ]
