# Generated by Django 2.0.3 on 2019-04-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_comparisons', '0003_auto_20190408_1835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandcomparisonsegmentrow',
            unique_together={('segment', 'ordering')},
        ),
    ]
