# Generated by Django 2.0.3 on 2019-11-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0062_auto_20190906_1534'),
        ('brand_comparisons', '0005_auto_20190416_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcomparison',
            name='manual_products',
            field=models.ManyToManyField(to='solotodo.Product'),
        ),
    ]
