# Generated by Django 2.0.3 on 2019-12-05 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0062_auto_20190906_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand_comparisons', '0006_brandcomparison_manual_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandComparisonAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_check', models.DateTimeField()),
                ('brand_comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_comparisons.BrandComparison')),
                ('stores', models.ManyToManyField(to='solotodo.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
