# Generated by Django 2.0.3 on 2019-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_comparisons', '0007_brandcomparisonalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcomparisonalert',
            name='last_check',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
