# Generated by Django 2.0.3 on 2020-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_comparisons', '0008_auto_20191212_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcomparisonsegmentrow',
            name='is_product_1_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandcomparisonsegmentrow',
            name='is_product_2_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
