# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0008_auto_20171114_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Category')),
            ],
            options={
                'ordering': ('category', 'website', 'purpose'),
            },
        ),
        migrations.CreateModel(
            name='CategoryTemplatePurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_templates.CategoryTemplatePurpose'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Website'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytemplate',
            unique_together=set([('category', 'website', 'purpose')]),
        ),
    ]
