# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0084_apiclient'),
        ('category_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytemplate',
            options={'ordering': ('category', 'api_client', 'purpose')},
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='api_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solotodo.ApiClient'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categorytemplate',
            unique_together=set([('category', 'api_client', 'purpose')]),
        ),
    ]
