# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solotodo', '0007_auto_20171113_2039'),
        ('category_templates', '0002_auto_20171017_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytemplate',
            old_name='api_client',
            new_name='website',
        ),
        migrations.AlterModelOptions(
            name='categorytemplate',
            options={'ordering': ('category', 'website', 'purpose')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytemplate',
            unique_together=set([('category', 'website', 'purpose')]),
        ),
    ]
