# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_templates', '0003_remove_categorytemplate_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTemplateTarget',
        ),
    ]
