# Generated by Django 2.2.13 on 2022-08-10 19:21

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0069_rating_email_or_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSlideAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', sorl.thumbnail.fields.ImageField(upload_to='website_slides')),
                ('theme_color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_url', models.URLField()),
                ('category_priority', models.IntegerField(blank=True, null=True)),
                ('home_priority', models.IntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_slides.WebsiteSlideAsset')),
                ('categories', models.ManyToManyField(to='solotodo.Category')),
            ],
        ),
    ]
