# Generated by Django 2.2.13 on 2022-08-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_slides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteslide',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
