# Generated by Django 2.0 on 2018-01-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='path',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navsection',
            name='path',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
    ]
