# Generated by Django 2.0 on 2018-01-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20180126_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.NavSection'),
        ),
        migrations.AlterField(
            model_name='navsection',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='navigation.NavDepartment'),
        ),
    ]
