# Generated by Django 2.2.13 on 2022-08-23 18:56

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_auto_20180126_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='nav_items'),
        ),
        migrations.AddField(
            model_name='navitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
