# Generated by Django 2.0 on 2018-02-23 12:44

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solotodo', '0018_category_budget_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_400', sorl.thumbnail.fields.ImageField(upload_to='carousel_slides')),
                ('img_576', sorl.thumbnail.fields.ImageField(upload_to='carousel_slides')),
                ('img_768', sorl.thumbnail.fields.ImageField(upload_to='carousel_slides')),
                ('img_992', sorl.thumbnail.fields.ImageField(upload_to='carousel_slides')),
                ('img_1200', sorl.thumbnail.fields.ImageField(upload_to='carousel_slides')),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solotodo.Website')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
