# Generated by Django 2.0 on 2018-02-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_slides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='target_url',
            field=models.URLField(default='https://www.solotodo.com/'),
            preserve_default=False,
        ),
    ]
